apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z4dr1s0nm-nodejs 
  janus-idp.io/tekton: z4dr1s0nm-nodejs
  backstage.io/kubernetes-id: z4dr1s0nm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z4dr1s0nm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml