apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z4dr1s0nm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z4dr1s0nm-nodejs 
  name: z4dr1s0nm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: z4dr1s0nm-nodejs 
